title: Rodney!
logo: /assets/img/logo.png
email: rodneyelevator
description: I make things out of stuff
show_downloads: false
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/rodneyrodneybristol
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/rodneyrodneybristol
  - name: AnotherPage
    icon: <i class="fa-regular fa-folder"></i>
    link: https://www.google.com
  
    

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
remote_theme: BDHU/minimalist
